### ISSUE TITLE
[Bug]: Typo inside Atom creation window

### ISSUE THREAD

**Issue by BuonHobo** [AtomsDevs/Atoms#15]
### Describe the bug

As you can see [here](https://raw.githubusercontent.com/AtomsDevs/Atoms/main/screenshot.png), it says "Downloading Choosen Image" but it's supposed to be spelled as "Chosen"

### To Reproduce

Just create a new Atom and you'll see the typo

### Package

Flatpak from Flathub

### Distribution

Fedora 36 Silverblue

### Display Protocol

Wayland

### Additional context

I'm sorry if this sounds nit-picky. I actually really value your work and I hope that I don't come across as annoying

**Comment by mirkobrombin** [comment]
Thanks for reporting
