### ISSUE TITLE
the icon doesn't seem like it belongs in gnome

### ISSUE THREAD

**Issue by allaeddineomc** [AtomsDevs/Atoms#16]
both the app icon and the symbolic icon aren't following gnome design guidelines

**Comment by allaeddineomc** [comment]
what do you think of something less detailed like this

![atoms](https://user-images.githubusercontent.com/57415185/188619044-384c7ebf-839d-48d4-94cf-b03c0c1cfee2.png)

**Comment by mirkobrombin** [comment]
I agree on the logo but I didn't give it too much importance. Your idea is not bad but in small size it lacks contrast, it looks like a purple balloon
