### ISSUE TITLE
[Request]: alias servicectl to systemctl

### ISSUE THREAD

**Issue by allaeddineomc** [AtomsDevs/Atoms#17]
### Tell us the problem or your need

some programs and scripts are hard coded to use systemctl and won't work on a chroot or a container without being modified 

### Describe the solution you'd like

make running systemcl executes servicestl instead

**Comment by mirkobrombin** [comment]
I wonder if this could cause any problems

**Comment by allaeddineomc** [comment]
i don't think it will be a problem since systemctl won't work anyway

**Comment by mirkobrombin** [comment]
Closed by https://github.com/AtomsDevs/atoms-core/commit/b5b2d16bfe314acee196fe404ba27cff16b4a21d
