### ISSUE TITLE
How do I give atoms access to org.freedesktop.Flatpak?

### ISSUE THREAD

**Issue by aadilayub** [AtomsDevs/Atoms#21]
From the README:

> To enable the distrobox integration, you need to give Atoms the Flatpak permission to talk to org.freedesktop.Flatpak.

How can one do this? I tried to look for the permission in Flatseal and it isn't exposed there. I couldn't figure it out by looking at the [Flatpak documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html) either.

**Comment by mirkobrombin** [comment]
The easiest way is to install Flatseal then look for the Atoms app in the left menu and add org.freedesktop.Flatpak as a Session talk

**Comment by aadilayub** [comment]
Thanks!
