### ISSUE TITLE
[Bug]: ":" are being escaped when typing the image name

### ISSUE THREAD

**Issue by nacho-domatix** [AtomsDevs/Atoms#24]
Hi, I'm sorry if the question is too obvious, but I've installed the app "out of the box" using Flatpak and I don't see the way to create containers. I have a question too, are they based in anyway on LXC?

![image](https://user-images.githubusercontent.com/28144115/189676571-4255c15c-b509-4c4c-83a3-c588c086ac1b.png)

**Comment by mirkobrombin** [comment]
Using Flatseal add a new entry in Talks->Session: `org.freedesktop.Flatpak` then restart Atoms

**Comment by nacho-domatix** [comment]
Hi @mirkobrombin and many thanks for the response. I installed Flatseal, and the only option similar I see is "Habla" (kind of talks in Spanish)

**Comment by mirkobrombin** [comment]
"Session" Bus not "System" Bus

**Comment by nacho-domatix** [comment]
Thanks, and sorry I didn't see it. But still, not working :(

**Comment by mirkobrombin** [comment]
Did you enable distrobox in the Atoms settings? Is distrobox in your PATH?

**Comment by nacho-domatix** [comment]
![imagen](https://user-images.githubusercontent.com/28144115/189826706-7fa6a246-0068-4e67-ac18-9b513d2d7ffd.png)

This is what I get, I'm sure I'm not doing everything properly but I'm not an expert.

**Comment by mirkobrombin** [comment]
Which  image did you choose for the container? Write the exact name because at the moment atoms does not check if the image exists and still try to create the container
