### ISSUE TITLE
[Request]: Reuse distrobox

### ISSUE THREAD

**Issue by Darin755** [AtomsDevs/Atoms#29]
### Tell us the problem or your need

It seems like a lot of work to recreate the work done by [distrobox](https://github.com/89luca89/distrobox). 

### Describe the solution you'd like

It might be possible to reuse some of the images created by distrobox. They have different configurations but in theory it could be made to work.

### Other solutions?

Atoms could become a frontend for ```distrobox```. This would eliminate the burden for maintaining images but would make most of the existing project worthless.

### Additional context and references

[distrobox](https://github.com/89luca89/distrobox)

[distrobox images](https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#containers-distros)

**Comment by mirkobrombin** [comment]
Distrobox support is already available in Atoms thanks to a collaboration with Luca (the author of distrobox).
