### ISSUE TITLE
Distrobox integration not working, even after changing permissions.

### ISSUE THREAD

**Issue by michaelkornblum** [AtomsDevs/Atoms#35]
So far, I'm enjoying the product, but as of yet, I've been unable to activate distrobox integrations. I've adjusted the talk permissions using flatseal to org.freedesktop.Flatpak and it's still not working. Am I doing something wrong here?

**Comment by mirkobrombin** [comment]
Enable D-Bus session bus
![image](https://user-images.githubusercontent.com/9479903/201025129-90238a77-7588-4a2e-8029-83ced6d47e8c.png)

Also, is distrobox installed in the host system and available in PATH?

**Comment by michaelkornblum** [comment]
Enabled D-Buse session bus on FlatSeal and Distrobox is installed and
available from the command line. Still no luck. Running Ubunto Studio 22.04
if that helps.

**Comment by michaelkornblum** [comment]
So I may have stumbled across the solution. In addition to enabling the
dbus session parameter in flatseal, I added the org.freedesktop.Flatpak
entry to both the session bus and system bus parameters. Thank you very
much for your time and support.

**Comment by mirkobrombin** [comment]
Nice, closing and following the other discussion
