### ISSUE TITLE
TypeError: AtomsWindow.on_btn_new_clicked() missing 1 required positional argument: 'action'

### ISSUE THREAD

**Issue by Samega7Cattac** [AtomsDevs/Atoms#46]
Every time I click on the create atom button I get
```
TypeError: AtomsWindow.on_btn_new_clicked() missing 1 required positional argument: 'action'
```
Fresh install from flatpak
If I use the "+" button in the corner it works

**Comment by archer920** [comment]
@mirkobrombin I'm still seeing this issue after install from TypeError: AtomsWindow.on_btn_new_clicked() missing 1 required positional argument: 'action'. Has the fix been pushed yet?

![Screenshot from 2023-02-14 10-26-52](https://user-images.githubusercontent.com/10244433/218782339-2df3379f-d050-4fec-9fbf-9efae3035619.png)

**Comment by mirkobrombin** [comment]
No, I'll distribute it soon
