### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [AtomsDevs/Atoms#49]
The current summary "Easily manage Linux Chroot and Containers." is not ideal (too long, includes "easily", which is usually superfluous in summaries, and ends with a period). I think it could be simplified to something like "Manage Chroot and Containers".

These are the appdata summary guidelines: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata#summary

**Comment by mirkobrombin** [comment]
It's actually not quite ideal. I think I will go with "Manage Chroot and Containers". Thanks for your contribution (and the guidelines).
