### ISSUE TITLE
Distrobox Integration greyed out even after giving permissions

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [AtomsDevs/Atoms#60]
I have distrobox installed locally and setup locally on my SteamDeck because if the immutable filesystem. I installed Atoms, used flatseal to give it the permissions needed, and rebooted to make sure everything loads properly. After all that, the option for distrobox is still greyed out.

Is there something I'm missing? Does distrobox integration not work if it is installed locally? 

I did select system for installing both the Atoms package and Flatseal package and will be willing to reinstall them as user packages if needed.

**Comment by mirkobrombin** [comment]
Hi, can you check this? https://github.com/AtomsDevs/Atoms/issues/35

**Comment by LovecraftianGodsKiller** [comment]
So I wrote this issue report after having already checked any existing issue reports to see if anyone has already made an issue about it as it seemed like an issue multiple people could have. 

I had even checked the one you linked to, [#35](https://github.com/AtomsDevs/Atoms/issues/35), did everything it said, even rebooted my system, and the option is still greyed out

**Comment by mirkobrombin** [comment]
That's pretty weird. So you have distrobox in your system and D-Bus-session bus enabled and it is still not able to find dbox?
Which version of dbox is it? There are some updates not released yet to support latest dbox versions, could be related.

**Comment by LovecraftianGodsKiller** [comment]
I'm pretty it's 1.5.0.2. I reran the install script about a week ago. I ran `distrobox version` and saw 1.5.something.

So Atoms not being updated to support the latest version would make sense as to why it is still greyed out.

**Comment by mirkobrombin** [comment]
I'll serve the new update asap

**Comment by tarpediem** [comment]
I'm having the exact same issue on the steamdeck. distrobox version is 1.5.0.2 freshly installed. I gave the permissions also on flatseal but no luck.

**Comment by mirkobrombin** [comment]
Update sent to Flathub, it will take some time: https://buildbot.flathub.org/#/builders/6/builds/58109

**Comment by LovecraftianGodsKiller** [comment]
Great! Thanks!
