### ISSUE TITLE
[Bug]: Cannot launch AppImages

### ISSUE THREAD

**Issue by blacklightpy** [AtomsDevs/Atoms#65]
### Describe the bug

It says:
![2023-12-20_12-20-58](https://github.com/AtomsDevs/Atoms/assets/28739146/e718ff46-2466-4a84-9a85-70b107c503a7)

### To Reproduce

1. Open chroot
2. Install FUSE
3. Open AppImage

### Package

Flatpak from Flathub

### Distribution

Void Linux x86_64-musl

### Display Protocol

Wayland

### Additional context

I tried enabling all permissions via Flatseal, but to no avail.

**Comment by mirkobrombin** [comment]
Appimage(s) cannot work inside Atoms due to its structure. Use the distrobox integration instead, which provides a full container.
